services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Expose React app on port 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_USER=digital_housing1
      - DB_PASSWORD=Yared123
      - DB_NAME=digital_housing1
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: digital_housing1
      MYSQL_USER: digital_housing1
      MYSQL_PASSWORD: Yared123
    ports:
      - "3307:3306"  # Maps MySQL container's port 3306 to host 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
