services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Expose React app on port 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD="Yared(2723)"
      - DB_NAME=digital_housing
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Yared(2723)"
      MYSQL_DATABASE: digital_housing
      MYSQL_USER: myuser
      MYSQL_PASSWORD: "Yared(2723)"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
